# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-08 22:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolsite', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='address',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='phone',
        ),
        migrations.AddField(
            model_name='contact',
            name='contact_address',
            field=models.CharField(default='SOME STRING', max_length=200),
        ),
        migrations.AddField(
            model_name='contact',
            name='contact_email',
            field=models.CharField(default='SOME STRING', max_length=50),
        ),
        migrations.AddField(
            model_name='contact',
            name='contact_message',
            field=models.CharField(default='SOME STRING', max_length=500),
        ),
        migrations.AddField(
            model_name='contact',
            name='contact_name',
            field=models.CharField(default='SOME STRING', max_length=30),
        ),
        migrations.AddField(
            model_name='contact',
            name='contact_phone',
            field=models.IntegerField(default=123),
        ),
    ]
