# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-09 19:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolsite', '0002_auto_20180108_2322'),
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_name', models.CharField(max_length=50)),
                ('login_pw', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='contact',
            name='contact_address',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='contact_phone',
        ),
        migrations.AlterField(
            model_name='contact',
            name='contact_email',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='contact',
            name='contact_message',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='contact',
            name='contact_name',
            field=models.CharField(max_length=30),
        ),
    ]
