# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-09 19:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schoolsite', '0004_teacher_pic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='pic',
            new_name='image',
        ),
    ]
